language: node_js
node_js:
  - "12"

deploy:
  provider: script
  on:
    branch: master
  script: bash deploy.sh from master branch $TRAVIS_TAG
    - npm install --save-dev surge
    - ./deploy.sh $TRAVIS_TAG

