version: 2.1
orbs:
  node: circleci/node@4.2.1

jobs:
  npm_install:
    working_directory: ~/inspiring-booth
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          app-dir: ~/inspiring-booth
          cache-path: node_modules
          override-ci-command: npm i
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: npm test

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run: ./deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - npm_install
      - test:
          requires:
            - npm_install
      - deploy:
          requires:
            - test

